add photo
ElizPery/project-backend-DarkHorsesTeam pull request #25
Opened 2024-10-16 21:55 UTC by boomsik

Не знаю правильно ли я сделал все, но надеюсь что да, добавил обновление фото и загрузку и если нет то тоже добавил надо будет тестировать уже с твоей базой наверняка что-то не так плюс добавил новый файл не нашел его в проекте для загрузки картинки там сделал проверку на расширение картинки так как в дз у меня были проблемы только png and jpeg опять же надо протестить с твоей базой данных и твоим cloudinary)

2024-10-17 08:21 UTC, ElizPery requested changes

2024-10-17 08:21 UTC, ElizPery commented on src/db/initMongoConnection.js
У цьому файлі нічого змінювати не потрібно, поверніть будь ласка як було

2024-10-17 08:21 UTC, ElizPery commented on src/middlewares/upload.js
> +const storage = multer.memoryStorage();
Використайте будь ласка diskStorage, необхідно заванажувати файл до тимчасової папки, на всяк випадок

const storage = multer.diskStorage({
    destination: TEMP_UPLOAD_DIR,
    filename: (req, file, callback) => {
        const uniquePreffix = Date.now();
        callback(null, `${uniquePreffix}_${file.originalname}`);
    },
});

2024-10-17 08:21 UTC, ElizPery commented on src/routers/user.js
> +  upload.single('avatar'),
'photo' повинно приймати, а також можете будь ласка додати валідацію

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +  updateUserAvatarController,
імпортувати сервіс необхідно (змінити назву)

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +  try {
try catch не потрібен, для цього є в роутах ctrlWrapper

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +      if (avatarUrl) {
додайте умову   
if (env('ENABLE_CLOUDINARY') === 'true') тоді завантажувати до cloudinary
else тоді завантажувати локально

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +      const result = await cloudinary.uploader.upload(req.file.path);
краще винести функцію завантаження до cloudinary в файл в utils

import { v2 as cloudinary } from 'cloudinary';
import fs from 'node:fs/promises';
import { env } from './env.js';
import { CLOUDINARY } from '../constants/index.js';

cloudinary.config({
    secure: true,
    cloud_name: env(CLOUDINARY.CLOUD_NAME),
    api_key: env(CLOUDINARY.API_KEY),
    api_secret: env(CLOUDINARY.API_SECRET),
});

export const saveFileToCloudinary = async (file, folder) => {
    const response = await cloudinary.uploader.upload(file.path, {
        folder,
    });
    await fs.unlink(file.path);
    
    return response.secure_url;
};

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +      avatarUrl = result.secure_url;
Завантаження локально також необхідно додати, в utils file saveFileToUploadsDir.js

Ось так наприклад

import path from 'node:path';
import fs from 'node:fs/promises';
import { TEMP_UPLOAD_DIR, UPLOAD_DIR } from '../constants/index.js';

export const saveFileToUploadsDir = async (file) => {
    await fs.rename(
        path.join(TEMP_UPLOAD_DIR, file.filename),
        path.join(UPLOAD_DIR, file.filename),
    );

    return file.filename;
};

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +    let avatarUrl = req.user.photo || null;
щоб не плутатися, краще назвати photo, але не обов'язково

2024-10-17 08:21 UTC, ElizPery commented on src/controllers/user.js
> +      status: 'success',
Щоб всюди було однаково краще писати status: 200

2024-10-17 20:18 UTC, boomsik commented on src/db/initMongoConnection.js
import mongoose from "mongoose";
import { env } from "../utils/env.js";
import mongoose from 'mongoose';
import { env } from '../utils/env.js';
это я не могу исправить к сожелению вам прийдеться делать это самой так как мой претиер не хочет ставить две скобочки я уже не знаю как это исправить

2024-10-17 20:18 UTC, boomsik commented on src/middlewares/upload.js
> +const storage = multer.memoryStorage();
сделал

2024-10-17 20:18 UTC, boomsik commented on src/routers/user.js
> +  upload.single('avatar'),
сделал

2024-10-17 20:18 UTC, boomsik commented on src/controllers/user.js
> +  updateUserAvatarController,
сделал

2024-10-17 20:18 UTC, boomsik commented on src/controllers/user.js
> +  try {
сделал

2024-10-17 20:19 UTC, boomsik commented on src/controllers/user.js
> +      const result = await cloudinary.uploader.upload(req.file.path);
сделал

2024-10-17 20:19 UTC, boomsik commented on src/controllers/user.js
> +      avatarUrl = result.secure_url;
сделал

2024-10-17 20:19 UTC, boomsik commented on src/controllers/user.js
> +    let avatarUrl = req.user.photo || null;
сделал

2024-10-17 20:19 UTC, boomsik commented on src/controllers/user.js
> +      status: 'success',
сделал

2024-10-17 20:19 UTC, boomsik commented on src/controllers/user.js
> +      if (avatarUrl) {
сделал

2024-10-17 20:20 UTC, boomsik commented on src/routers/user.js
> +  upload.single('avatar'),
тут немного не понял за валидацию, простите)

2024-10-18 07:12 UTC, ElizPery requested changes

2024-10-18 07:12 UTC, ElizPery commented on src/controllers/user.js
> +  let avatarUrl = req.user.photo || null;
тут можна не ставити null, тому що у цьому роуті photo обов'язкове

2024-10-18 07:12 UTC, ElizPery commented on src/middlewares/upload.js
> +const TEMP_UPLOAD_DIR = './temp';
import { TEMP_UPLOAD_DIR } from '../constants/index.js';


цей шлях з констант

2024-10-18 07:12 UTC, ElizPery commented on src/routers/user.js
> +  upload.single('photo'),
тут ще додати validateBody(updateUserAvatarSchema)


у файлі validation/users створити Joi схему

export const updatePhotoUserSchema = Joi.object({
photo: Joi.string().required(),
});

2024-10-18 07:12 UTC, ElizPery commented on src/utils/cloudinary.js
> +dotenv.config();
dotenv не потрібен, є спеціальна функція в utils/env.js

2024-10-18 07:12 UTC, ElizPery commented on src/utils/cloudinary.js
> +  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
process.env відповідно також 

import { env } from './env.js';

cloud_name: env(CLOUDINARY.CLOUD_NAME),
    api_key: env(CLOUDINARY.API_KEY),
    api_secret: env(CLOUDINARY.API_SECRET),

2024-10-18 07:12 UTC, ElizPery commented on src/utils/fileUpload.js
> +dotenv.config();
тут теж саме, є спеціальна функція в utils/env.js

2024-10-18 19:45 UTC, boomsik commented on src/utils/fileUpload.js
> +dotenv.config();
сделал

2024-10-18 19:45 UTC, boomsik commented on src/utils/cloudinary.js
> +  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
сделал

2024-10-18 19:45 UTC, boomsik commented on src/utils/cloudinary.js
> +dotenv.config();
сделал

2024-10-18 19:45 UTC, boomsik commented on src/routers/user.js
> +  upload.single('photo'),
сделал

2024-10-18 19:46 UTC, boomsik commented on src/controllers/user.js
> +  let avatarUrl = req.user.photo || null;
сделал прости что так поздно недавно пришле с работы , завтра просмотрю всю инфу еще раз что вы там наговорили)

2024-10-19 08:21 UTC, ElizPery requested changes

2024-10-19 08:21 UTC, ElizPery commented on src/middlewares/upload.js
> +const TEMP_UPLOAD_DIR = './temp';
Не виправили ось це

import { TEMP_UPLOAD_DIR } from '../constants/index.js';

цей шлях з констант

2024-10-19 08:21 UTC, ElizPery commented on src/controllers/user.js
> +  let avatarUrl = req.user.photo;
Та ось тут req.body.photo в минулий раз не звернула уваги, photo передається в req.body

2024-10-19 12:19 UTC, boomsik commented on src/middlewares/upload.js
> +const TEMP_UPLOAD_DIR = './temp';
сделал

2024-10-19 12:19 UTC, boomsik commented on src/controllers/user.js
> +  let avatarUrl = req.user.photo;
сделал

2024-10-19 13:30 UTC, ElizPery approved these changes

2024-10-19 13:30 UTC, merged